repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
        args: [--line-length=135]
-   repo: local
    hooks:
      - id: snyk-test
        name: Snyk Test
        entry: bash -c 'snyk test --fail-on=upgradable'
        language: system
